// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bK6Pj2aRyaO_NZJGWPKa2jZJnbqYv8w',
    appId: '1:601969263054:web:3229a09ec8229c7046eb9f',
    messagingSenderId: '601969263054',
    projectId: 'to-do-backend-b9085',
    authDomain: 'to-do-backend-b9085.firebaseapp.com',
    storageBucket: 'to-do-backend-b9085.appspot.com',
    measurementId: 'G-RE71CDLW81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3qobMFSBLMOcZHQnQ5GY--7GqztEtLY',
    appId: '1:601969263054:android:d7706ca521fe502b46eb9f',
    messagingSenderId: '601969263054',
    projectId: 'to-do-backend-b9085',
    storageBucket: 'to-do-backend-b9085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcX105Bsk3jx-yf_mbVhMvmn1DLAqAvs',
    appId: '1:601969263054:ios:70de6029b93489a446eb9f',
    messagingSenderId: '601969263054',
    projectId: 'to-do-backend-b9085',
    storageBucket: 'to-do-backend-b9085.appspot.com',
    iosClientId: '601969263054-ci49heitjo3d01qje2jok4a0sn93e4mt.apps.googleusercontent.com',
    iosBundleId: 'de.domephant.todo',
  );
}
